### ISSUE TITLE
`Configuring accelerators with optional dependencies` from docs fails

### ISSUE THREAD

**Issue by jplumail** [astral-sh/uv#9419]
Hi !

I was testing using uv with PyTorch and ran into this issue.

I copy-pasted the `pyproject.toml` from the [docs](https://docs.astral.sh/uv/guides/integration/pytorch/#configuring-accelerators-with-optional-dependencies):
```toml
[project]
name = "project"
version = "0.1.0"
requires-python = ">=3.12.0"
dependencies = []

[project.optional-dependencies]
cpu = [
  "torch>=2.5.1",
  "torchvision>=0.20.1",
]
cu124 = [
  "torch>=2.5.1",
  "torchvision>=0.20.1",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu124" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu", marker = "platform_system != 'Darwin'" },
  { index = "pytorch-cu124", extra = "cu124" },
]
torchvision = [
  { index = "pytorch-cpu", extra = "cpu", marker = "platform_system != 'Darwin'" },
  { index = "pytorch-cu124", extra = "cu124" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true
```

<details>
<summary>uv sync and the verbose output</summary>

```sh
$ uv sync --extra cu124 -v
DEBUG uv 0.5.4 (c62c83c37 2024-11-20)
DEBUG Found project root: `C:\Users\jeanp\code\tmp`
DEBUG No workspace root found, using project root
DEBUG Using Python request `>=3.12.0` from `requires-python` metadata
DEBUG The virtual environment's Python version satisfies `>=3.12.0`
DEBUG Using request timeout of 30s
DEBUG Found static `pyproject.toml` for: project @ file:///C:/Users/jeanp/code/tmp
DEBUG No workspace root found, using project root
DEBUG Solving with installed Python version: 3.13.0
DEBUG Solving with target Python version: >=3.12.0
DEBUG Pre-fork all marker environments took 0.000s
DEBUG Splitting resolution on root==0a0.dev0 over project into 3 resolution with separate markers
DEBUG Adding direct dependency: project*
DEBUG Adding direct dependency: project*
DEBUG Adding direct dependency: project[cpu]*
DEBUG Adding direct dependency: project*
DEBUG Adding direct dependency: project[cu124]*
DEBUG Searching for a compatible version of project @ file:///C:/Users/jeanp/code/tmp (*)
DEBUG Adding transitive dependency for project==0.1.0: project==0.1.0
DEBUG Adding transitive dependency for project==0.1.0: project[cu124]==0.1.0
DEBUG Searching for a compatible version of project @ file:///C:/Users/jeanp/code/tmp (==0.1.0)
DEBUG Searching for a compatible version of project @ file:///C:/Users/jeanp/code/tmp (==0.1.0)
DEBUG Adding transitive dependency for project==0.1.0: torch>=2.5.1
DEBUG Adding transitive dependency for project==0.1.0: torchvision>=0.20.1
DEBUG No cache entry for: https://download.pytorch.org/whl/cu124/torch/
DEBUG No cache entry for: https://download.pytorch.org/whl/cu124/torchvision/
DEBUG Searching for a compatible version of torch (>=2.5.1)
DEBUG Selecting: torch==2.5.1+cu124 [compatible] (torch-2.5.1+cu124-cp312-cp312-linux_x86_64.whl)
DEBUG Found stale response for: https://download.pytorch.org/whl/cu124/torch-2.5.1%2Bcu124-cp312-cp312-linux_x86_64.whl#sha256=bf6484bfe5bc4f92a4a1a1bf553041505e19a911f717065330eb061afe0e14d7
DEBUG Sending revalidation request for: https://download.pytorch.org/whl/cu124/torch-2.5.1%2Bcu124-cp312-cp312-linux_x86_64.whl#sha256=bf6484bfe5bc4f92a4a1a1bf553041505e19a911f717065330eb061afe0e14d7
DEBUG Found not-modified response for: https://download.pytorch.org/whl/cu124/torch-2.5.1%2Bcu124-cp312-cp312-linux_x86_64.whl#sha256=bf6484bfe5bc4f92a4a1a1bf553041505e19a911f717065330eb061afe0e14d7
DEBUG Adding transitive dependency for torch==2.5.1+cu124: filelock*
DEBUG Adding transitive dependency for torch==2.5.1+cu124: fsspec*
DEBUG Adding transitive dependency for torch==2.5.1+cu124: jinja2*
DEBUG Adding transitive dependency for torch==2.5.1+cu124: networkx*
DEBUG Adding transitive dependency for torch==2.5.1+cu124: nvidia-cublas-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}>=12.4.5.8, <12.4.5.8+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: nvidia-cuda-cupti-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}>=12.4.127, <12.4.127+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: nvidia-cuda-nvrtc-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}>=12.4.127, <12.4.127+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: nvidia-cuda-runtime-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}>=12.4.127, <12.4.127+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: nvidia-cudnn-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}>=9.1.0.70, <9.1.0.70+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: nvidia-cufft-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}>=11.2.1.3, <11.2.1.3+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: nvidia-curand-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}>=10.3.5.147, <10.3.5.147+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: nvidia-cusolver-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}>=11.6.1.9, <11.6.1.9+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: nvidia-cusparse-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}>=12.3.1.170, <12.3.1.170+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: nvidia-nccl-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}>=2.21.5, <2.21.5+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: nvidia-nvjitlink-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}>=12.4.127, <12.4.127+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: nvidia-nvtx-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}>=12.4.127, <12.4.127+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: setuptools{python_full_version >= '3.12'}*
DEBUG Adding transitive dependency for torch==2.5.1+cu124: sympy{python_full_version >= '3.9'}>=1.13.1, <1.13.1+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: triton{python_full_version < '3.13' and platform_machine == 'x86_64' and platform_system == 'Linux'}>=3.1.0, <3.1.0+
DEBUG Adding transitive dependency for torch==2.5.1+cu124: typing-extensions>=4.8.0
DEBUG Searching for a compatible version of torchvision (>=0.20.1)
DEBUG Found fresh response for: https://pypi.org/simple/filelock/
DEBUG Selecting: torchvision==0.20.1+cu124 [compatible] (torchvision-0.20.1+cu124-cp312-cp312-linux_x86_64.whl)
DEBUG Found fresh response for: https://pypi.org/simple/jinja2/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cublas-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/networkx/
DEBUG Found fresh response for: https://pypi.org/simple/fsspec/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cuda-cupti-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cudnn-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cufft-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cuda-nvrtc-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cuda-runtime-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cusolver-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-nccl-cu12/
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/b9/f8/feced7779d755758a52d1f6635d990b8d98dc0a29fa568bbe0625f18fdf3/filelock-3.16.1-py3-none-any.whl.metadata
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-nvjitlink-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-curand-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/sympy/
DEBUG Found fresh response for: https://pypi.org/simple/triton/
DEBUG Found fresh response for: https://pypi.org/simple/typing-extensions/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-nvtx-cu12/
DEBUG Found fresh response for: https://pypi.org/simple/setuptools/
DEBUG Found fresh response for: https://pypi.org/simple/nvidia-cusparse-cu12/
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/31/80/3a54838c3fb461f6fec263ebf3a3a41771bd05190238de3486aae8540c36/jinja2-3.1.4-py3-none-any.whl.metadata
DEBUG Found stale response for: https://download.pytorch.org/whl/cu124/torchvision-0.20.1%2Bcu124-cp312-cp312-linux_x86_64.whl#sha256=d1053ec5054549e7dac2613b151bffe323f3c924939d296df4d7d34925aaf3ad
DEBUG Sending revalidation request for: https://download.pytorch.org/whl/cu124/torchvision-0.20.1%2Bcu124-cp312-cp312-linux_x86_64.whl#sha256=d1053ec5054549e7dac2613b151bffe323f3c924939d296df4d7d34925aaf3ad
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/b9/54/dd730b32ea14ea797530a4479b2ed46a6fb250f682a9cfb997e968bf0261/networkx-3.4.2-py3-none-any.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/c6/b2/454d6e7f0158951d8a78c2e1eb4f69ae81beb8dca5fee9809c6c99e9d0d0/fsspec-2024.10.0-py3-none-any.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/26/9f/ad63fc0248c5379346306f8668cda6e2e2e9c95e01216d2b8ffd9ff037d0/typing_extensions-4.12.2-py3-none-any.whl.metadata
DEBUG Found not-modified response for: https://download.pytorch.org/whl/cu124/torchvision-0.20.1%2Bcu124-cp312-cp312-linux_x86_64.whl#sha256=d1053ec5054549e7dac2613b151bffe323f3c924939d296df4d7d34925aaf3ad
DEBUG Adding transitive dependency for torchvision==0.20.1+cu124: numpy*
DEBUG Adding transitive dependency for torchvision==0.20.1+cu124: pillow>=5.3.0, <8.3.dev0 | >=8.4.dev0
DEBUG Adding transitive dependency for torchvision==0.20.1+cu124: torch>=2.5.1, <2.5.1+
DEBUG Searching for a compatible version of filelock (*)
DEBUG Selecting: filelock==3.16.1 [compatible] (filelock-3.16.1-py3-none-any.whl)
DEBUG Found fresh response for: https://pypi.org/simple/pillow/
DEBUG Searching for a compatible version of fsspec (*)
DEBUG Selecting: fsspec==2024.10.0 [compatible] (fsspec-2024.10.0-py3-none-any.whl)
DEBUG Searching for a compatible version of jinja2 (*)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/1c/a3/26e606ff0b2daaf120543e537311fa3ae2eb6bf061490e4fea51771540be/pillow-11.0.0-cp312-cp312-macosx_10_13_x86_64.whl.metadata
DEBUG Selecting: jinja2==3.1.4 [compatible] (jinja2-3.1.4-py3-none-any.whl)
DEBUG Found fresh response for: https://pypi.org/simple/numpy/
DEBUG Adding transitive dependency for jinja2==3.1.4: markupsafe>=2.0
DEBUG Searching for a compatible version of networkx (*)
DEBUG Selecting: networkx==3.4.2 [compatible] (networkx-3.4.2-py3-none-any.whl)
DEBUG Searching for a compatible version of nvidia-cublas-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (>=12.4.5.8, <12.4.5.8+)
DEBUG Selecting: nvidia-cublas-cu12==12.4.5.8 [compatible] (nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cublas-cu12==12.4.5.8: nvidia-cublas-cu12==12.4.5.8
DEBUG Adding transitive dependency for nvidia-cublas-cu12==12.4.5.8: nvidia-cublas-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==12.4.5.8
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/8a/f0/385eb9970309643cbca4fc6eebc8bb16e560de129c91258dfaa18498da8b/numpy-2.1.3-cp312-cp312-macosx_10_13_x86_64.whl.metadata
DEBUG Searching for a compatible version of nvidia-cublas-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (==12.4.5.8)
DEBUG Selecting: nvidia-cublas-cu12==12.4.5.8 [compatible] (nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/7f/7f/7fbae15a3982dc9595e49ce0f19332423b260045d0a6afe93cdbe2f1f624/nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Found fresh response for: https://pypi.org/simple/markupsafe/
DEBUG Searching for a compatible version of nvidia-cublas-cu12 (==12.4.5.8)
DEBUG Selecting: nvidia-cublas-cu12==12.4.5.8 [compatible] (nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-cupti-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (>=12.4.127, <12.4.127+)
DEBUG Selecting: nvidia-cuda-cupti-cu12==12.4.127 [compatible] (nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cuda-cupti-cu12==12.4.127: nvidia-cuda-cupti-cu12==12.4.127
DEBUG Adding transitive dependency for nvidia-cuda-cupti-cu12==12.4.127: nvidia-cuda-cupti-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==12.4.127
DEBUG Searching for a compatible version of nvidia-cuda-cupti-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (==12.4.127)   
DEBUG Selecting: nvidia-cuda-cupti-cu12==12.4.127 [compatible] (nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/22/09/d1f21434c97fc42f09d290cbb6350d44eb12f09cc62c9476effdb33a18aa/MarkupSafe-3.0.2-cp312-cp312-macosx_10_13_universal2.whl.metadata
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/93/b5/9fb3d00386d3361b03874246190dfec7b206fd74e6e287b26a8fcb359d95/nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-cuda-cupti-cu12 (==12.4.127)
DEBUG Selecting: nvidia-cuda-cupti-cu12==12.4.127 [compatible] (nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-nvrtc-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (>=12.4.127, <12.4.127+)
DEBUG Selecting: nvidia-cuda-nvrtc-cu12==12.4.127 [compatible] (nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cuda-nvrtc-cu12==12.4.127: nvidia-cuda-nvrtc-cu12==12.4.127
DEBUG Adding transitive dependency for nvidia-cuda-nvrtc-cu12==12.4.127: nvidia-cuda-nvrtc-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==12.4.127
DEBUG Searching for a compatible version of nvidia-cuda-nvrtc-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (==12.4.127)   
DEBUG Selecting: nvidia-cuda-nvrtc-cu12==12.4.127 [compatible] (nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/77/aa/083b01c427e963ad0b314040565ea396f914349914c298556484f799e61b/nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-cuda-nvrtc-cu12 (==12.4.127)
DEBUG Selecting: nvidia-cuda-nvrtc-cu12==12.4.127 [compatible] (nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cuda-runtime-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (>=12.4.127, <12.4.127+)
DEBUG Selecting: nvidia-cuda-runtime-cu12==12.4.127 [compatible] (nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)        
DEBUG Adding transitive dependency for nvidia-cuda-runtime-cu12==12.4.127: nvidia-cuda-runtime-cu12==12.4.127
DEBUG Adding transitive dependency for nvidia-cuda-runtime-cu12==12.4.127: nvidia-cuda-runtime-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==12.4.127
DEBUG Searching for a compatible version of nvidia-cuda-runtime-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (==12.4.127)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/a1/aa/b656d755f474e2084971e9a297def515938d56b466ab39624012070cb773/nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Selecting: nvidia-cuda-runtime-cu12==12.4.127 [compatible] (nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)        
DEBUG Searching for a compatible version of nvidia-cuda-runtime-cu12 (==12.4.127)
DEBUG Selecting: nvidia-cuda-runtime-cu12==12.4.127 [compatible] (nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)        
DEBUG Searching for a compatible version of nvidia-cudnn-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (>=9.1.0.70, <9.1.0.70+)
DEBUG Selecting: nvidia-cudnn-cu12==9.1.0.70 [compatible] (nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl)
DEBUG Adding transitive dependency for nvidia-cudnn-cu12==9.1.0.70: nvidia-cudnn-cu12==9.1.0.70
DEBUG Adding transitive dependency for nvidia-cudnn-cu12==9.1.0.70: nvidia-cudnn-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==9.1.0.70
DEBUG Searching for a compatible version of nvidia-cudnn-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (==9.1.0.70)        
DEBUG Selecting: nvidia-cudnn-cu12==9.1.0.70 [compatible] (nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/9f/fd/713452cd72343f682b1c7b9321e23829f00b842ceaedcda96e742ea0b0b3/nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata
DEBUG Adding transitive dependency for nvidia-cudnn-cu12==9.1.0.70: nvidia-cublas-cu12*
DEBUG Searching for a compatible version of nvidia-cudnn-cu12 (==9.1.0.70)
DEBUG Selecting: nvidia-cudnn-cu12==9.1.0.70 [compatible] (nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl)
DEBUG Adding transitive dependency for nvidia-cudnn-cu12==9.1.0.70: nvidia-cublas-cu12*
DEBUG Searching for a compatible version of nvidia-cufft-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (>=11.2.1.3, <11.2.1.3+)
DEBUG Selecting: nvidia-cufft-cu12==11.2.1.3 [compatible] (nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cufft-cu12==11.2.1.3: nvidia-cufft-cu12==11.2.1.3
DEBUG Adding transitive dependency for nvidia-cufft-cu12==11.2.1.3: nvidia-cufft-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==11.2.1.3
DEBUG Searching for a compatible version of nvidia-cufft-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (==11.2.1.3)        
DEBUG Selecting: nvidia-cufft-cu12==11.2.1.3 [compatible] (nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/7a/8a/0e728f749baca3fbeffad762738276e5df60851958be7783af121a7221e7/nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Adding transitive dependency for nvidia-cufft-cu12==11.2.1.3: nvidia-nvjitlink-cu12*
DEBUG Searching for a compatible version of nvidia-cufft-cu12 (==11.2.1.3)
DEBUG Selecting: nvidia-cufft-cu12==11.2.1.3 [compatible] (nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cufft-cu12==11.2.1.3: nvidia-nvjitlink-cu12*
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/9d/d7/c5383e47c7e9bf1c99d5bd2a8c935af2b6d705ad831a7ec5c97db4d82f4f/nvidia_nvjitlink_cu12-12.6.85-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata
DEBUG Searching for a compatible version of nvidia-curand-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (>=10.3.5.147, <10.3.5.147+)
DEBUG Selecting: nvidia-curand-cu12==10.3.5.147 [compatible] (nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-curand-cu12==10.3.5.147: nvidia-curand-cu12==10.3.5.147
DEBUG Adding transitive dependency for nvidia-curand-cu12==10.3.5.147: nvidia-curand-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==10.3.5.147
DEBUG Searching for a compatible version of nvidia-curand-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (==10.3.5.147)     
DEBUG Selecting: nvidia-curand-cu12==10.3.5.147 [compatible] (nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/80/9c/a79180e4d70995fdf030c6946991d0171555c6edf95c265c6b2bf7011112/nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-curand-cu12 (==10.3.5.147)
DEBUG Selecting: nvidia-curand-cu12==10.3.5.147 [compatible] (nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-cusolver-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (>=11.6.1.9, <11.6.1.9+)
DEBUG Selecting: nvidia-cusolver-cu12==11.6.1.9 [compatible] (nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.6.1.9: nvidia-cusolver-cu12==11.6.1.9
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.6.1.9: nvidia-cusolver-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==11.6.1.9
DEBUG Searching for a compatible version of nvidia-cusolver-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (==11.6.1.9)     
DEBUG Selecting: nvidia-cusolver-cu12==11.6.1.9 [compatible] (nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/46/6b/a5c33cf16af09166845345275c34ad2190944bcc6026797a39f8e0a282e0/nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.6.1.9: nvidia-cublas-cu12*
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.6.1.9: nvidia-cusparse-cu12*
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.6.1.9: nvidia-nvjitlink-cu12*
DEBUG Searching for a compatible version of nvidia-cusolver-cu12 (==11.6.1.9)
DEBUG Selecting: nvidia-cusolver-cu12==11.6.1.9 [compatible] (nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.6.1.9: nvidia-cublas-cu12*
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.6.1.9: nvidia-cusparse-cu12*
DEBUG Adding transitive dependency for nvidia-cusolver-cu12==11.6.1.9: nvidia-nvjitlink-cu12*
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/eb/eb/6681efd0aa7df96b4f8067b3ce7246833dd36830bb4cec8896182773db7d/nvidia_cusparse_cu12-12.5.4.2-py3-none-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-cusparse-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (>=12.3.1.170, <12.3.1.170+)
DEBUG Selecting: nvidia-cusparse-cu12==12.3.1.170 [compatible] (nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cusparse-cu12==12.3.1.170: nvidia-cusparse-cu12==12.3.1.170
DEBUG Adding transitive dependency for nvidia-cusparse-cu12==12.3.1.170: nvidia-cusparse-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==12.3.1.170
DEBUG Searching for a compatible version of nvidia-cusparse-cu12 (==12.3.1.170)
DEBUG Selecting: nvidia-cusparse-cu12==12.3.1.170 [compatible] (nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/96/a9/c0d2f83a53d40a4a41be14cea6a0bf9e668ffcf8b004bd65633f433050c0/nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Adding transitive dependency for nvidia-cusparse-cu12==12.3.1.170: nvidia-nvjitlink-cu12*
DEBUG Searching for a compatible version of nvidia-cusparse-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (==12.3.1.170)   
DEBUG Selecting: nvidia-cusparse-cu12==12.3.1.170 [compatible] (nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-cusparse-cu12==12.3.1.170: nvidia-nvjitlink-cu12*
DEBUG Searching for a compatible version of nvidia-nccl-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (>=2.21.5, <2.21.5+) 
DEBUG Selecting: nvidia-nccl-cu12==2.21.5 [compatible] (nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl)
DEBUG Adding transitive dependency for nvidia-nccl-cu12==2.21.5: nvidia-nccl-cu12==2.21.5
DEBUG Adding transitive dependency for nvidia-nccl-cu12==2.21.5: nvidia-nccl-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==2.21.5
DEBUG Searching for a compatible version of nvidia-nccl-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (==2.21.5)
DEBUG Selecting: nvidia-nccl-cu12==2.21.5 [compatible] (nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/df/99/12cd266d6233f47d00daf3a72739872bdc10267d0383508b0b9c84a18bb6/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl.metadata
DEBUG Searching for a compatible version of nvidia-nccl-cu12 (==2.21.5)
DEBUG Selecting: nvidia-nccl-cu12==2.21.5 [compatible] (nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl)
DEBUG Searching for a compatible version of nvidia-nvjitlink-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (>=12.4.127, <12.4.127+)
DEBUG Selecting: nvidia-nvjitlink-cu12==12.4.127 [compatible] (nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-nvjitlink-cu12==12.4.127: nvidia-nvjitlink-cu12==12.4.127
DEBUG Adding transitive dependency for nvidia-nvjitlink-cu12==12.4.127: nvidia-nvjitlink-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==12.4.127
DEBUG Searching for a compatible version of nvidia-nvjitlink-cu12 (==12.4.127)
DEBUG Selecting: nvidia-nvjitlink-cu12==12.4.127 [compatible] (nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/02/45/239d52c05074898a80a900f49b1615d81c07fceadd5ad6c4f86a987c0bc4/nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-nvjitlink-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (==12.4.127)    
DEBUG Selecting: nvidia-nvjitlink-cu12==12.4.127 [compatible] (nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of nvidia-nvtx-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (>=12.4.127, <12.4.127+)
DEBUG Selecting: nvidia-nvtx-cu12==12.4.127 [compatible] (nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)
DEBUG Adding transitive dependency for nvidia-nvtx-cu12==12.4.127: nvidia-nvtx-cu12==12.4.127
DEBUG Adding transitive dependency for nvidia-nvtx-cu12==12.4.127: nvidia-nvtx-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'}==12.4.127
DEBUG Searching for a compatible version of nvidia-nvtx-cu12{platform_machine == 'x86_64' and platform_system == 'Linux'} (==12.4.127)
DEBUG Selecting: nvidia-nvtx-cu12==12.4.127 [compatible] (nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/06/39/471f581edbb7804b39e8063d92fc8305bdc7a80ae5c07dbe6ea5c50d14a5/nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl.metadata
DEBUG Searching for a compatible version of nvidia-nvtx-cu12 (==12.4.127)
DEBUG Selecting: nvidia-nvtx-cu12==12.4.127 [compatible] (nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_aarch64.whl)
DEBUG Searching for a compatible version of setuptools{python_full_version >= '3.12'} (*)
DEBUG Selecting: setuptools==75.6.0 [compatible] (setuptools-75.6.0-py3-none-any.whl)
DEBUG Adding transitive dependency for setuptools==75.6.0: setuptools==75.6.0
DEBUG Adding transitive dependency for setuptools==75.6.0: setuptools{python_full_version >= '3.12'}==75.6.0
DEBUG Searching for a compatible version of setuptools{python_full_version >= '3.12'} (==75.6.0)
DEBUG Selecting: setuptools==75.6.0 [compatible] (setuptools-75.6.0-py3-none-any.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/55/21/47d163f615df1d30c094f6c8bbb353619274edccf0327b185cc2493c2c33/setuptools-75.6.0-py3-none-any.whl.metadata
DEBUG Searching for a compatible version of setuptools (==75.6.0)
DEBUG Selecting: setuptools==75.6.0 [compatible] (setuptools-75.6.0-py3-none-any.whl)
DEBUG Searching for a compatible version of sympy{python_full_version >= '3.9'} (>=1.13.1, <1.13.1+)
DEBUG Selecting: sympy==1.13.1 [compatible] (sympy-1.13.1-py3-none-any.whl)
DEBUG Adding transitive dependency for sympy==1.13.1: sympy==1.13.1
DEBUG Adding transitive dependency for sympy==1.13.1: sympy{python_full_version >= '3.9'}==1.13.1
DEBUG Searching for a compatible version of sympy{python_full_version >= '3.9'} (==1.13.1)
DEBUG Selecting: sympy==1.13.1 [compatible] (sympy-1.13.1-py3-none-any.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/b2/fe/81695a1aa331a842b582453b605175f419fe8540355886031328089d840a/sympy-1.13.1-py3-none-any.whl.metadata
DEBUG Adding transitive dependency for sympy==1.13.1: mpmath>=1.1.0, <1.4
DEBUG Searching for a compatible version of sympy (==1.13.1)
DEBUG Selecting: sympy==1.13.1 [compatible] (sympy-1.13.1-py3-none-any.whl)
DEBUG Found fresh response for: https://pypi.org/simple/mpmath/
DEBUG Adding transitive dependency for sympy==1.13.1: mpmath>=1.1.0, <1.4
DEBUG Searching for a compatible version of triton{python_full_version < '3.13' and platform_machine == 'x86_64' and platform_system == 'Linux'} (>=3.1.0, <3.1.0+)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/43/e3/7d92a15f894aa0c9c4b49b8ee9ac9850d6e63b03c9c32c0367a13ae62209/mpmath-1.3.0-py3-none-any.whl.metadata
DEBUG Selecting: triton==3.1.0 [compatible] (triton-3.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Adding transitive dependency for triton==3.1.0: triton==3.1.0
DEBUG Adding transitive dependency for triton==3.1.0: triton{python_full_version < '3.13' and platform_machine == 'x86_64' and platform_system == 'Linux'}==3.1.0
DEBUG Searching for a compatible version of triton{python_full_version < '3.13' and platform_machine == 'x86_64' and platform_system == 'Linux'} (==3.1.0)
DEBUG Selecting: triton==3.1.0 [compatible] (triton-3.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/78/eb/65f5ba83c2a123f6498a3097746607e5b2f16add29e36765305e4ac7fdd8/triton-3.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
DEBUG Adding transitive dependency for triton==3.1.0: filelock*
DEBUG Searching for a compatible version of triton (==3.1.0)
DEBUG Selecting: triton==3.1.0 [compatible] (triton-3.1.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)
DEBUG Adding transitive dependency for triton==3.1.0: filelock*
DEBUG Searching for a compatible version of typing-extensions (>=4.8.0)
DEBUG Selecting: typing-extensions==4.12.2 [compatible] (typing_extensions-4.12.2-py3-none-any.whl)
DEBUG Searching for a compatible version of numpy (*)
DEBUG Selecting: numpy==2.1.3 [compatible] (numpy-2.1.3-cp312-cp312-macosx_10_13_x86_64.whl)
DEBUG Searching for a compatible version of pillow (>=5.3.0, <8.3.dev0 | >=8.4.dev0)
DEBUG Selecting: pillow==11.0.0 [compatible] (pillow-11.0.0-cp312-cp312-macosx_10_13_x86_64.whl)
DEBUG Searching for a compatible version of markupsafe (>=2.0)
DEBUG Selecting: markupsafe==3.0.2 [compatible] (MarkupSafe-3.0.2-cp312-cp312-macosx_10_13_universal2.whl)
DEBUG Searching for a compatible version of mpmath (>=1.1.0, <1.4)
DEBUG Selecting: mpmath==1.3.0 [compatible] (mpmath-1.3.0-py3-none-any.whl)
DEBUG Tried 27 versions: filelock 1, fsspec 1, jinja2 1, markupsafe 1, mpmath 1, networkx 1, numpy 1, nvidia-cublas-cu12 1, nvidia-cuda-cupti-cu12 1, nvidia-cuda-nvrtc-cu12 1, nvidia-cuda-runtime-cu12 1, nvidia-cudnn-cu12 1, nvidia-cufft-cu12 1, nvidia-curand-cu12 1, nvidia-cusolver-cu12 1, nvidia-cusparse-cu12 1, nvidia-nccl-cu12 1, nvidia-nvjitlink-cu12 1, nvidia-nvtx-cu12 1, pillow 1, project 1, setuptools 1, sympy 1, torch 1, torchvision 1, triton 1, typing-extensions 1
DEBUG all marker environments resolution took 1.178s
DEBUG Searching for a compatible version of project @ file:///C:/Users/jeanp/code/tmp (*)
DEBUG Adding transitive dependency for project==0.1.0: project==0.1.0
DEBUG Adding transitive dependency for project==0.1.0: project[cpu]==0.1.0
DEBUG Searching for a compatible version of project @ file:///C:/Users/jeanp/code/tmp (==0.1.0)
DEBUG Searching for a compatible version of project @ file:///C:/Users/jeanp/code/tmp (==0.1.0)
DEBUG Pre-fork all marker environments took 0.003s
DEBUG Splitting resolution on project[cpu]==0.1.0 over torch, torchvision into 2 resolution with separate markers
DEBUG Adding transitive dependency for project==0.1.0: torch{platform_system == 'Darwin'}>=2.5.1
DEBUG Adding transitive dependency for project==0.1.0: torchvision{platform_system == 'Darwin'}>=0.20.1
DEBUG Adding transitive dependency for project==0.1.0: torch{platform_system != 'Darwin'}>=2.5.1
DEBUG Adding transitive dependency for project==0.1.0: torchvision{platform_system != 'Darwin'}>=0.20.1
DEBUG Solving split (platform_system != 'Darwin') (requires-python: RequiresPython { specifiers: VersionSpecifiers([VersionSpecifier { operator: GreaterThanEqual, version: "3.12.0" }]), range: RequiresPythonRange(LowerBound(Included("3.12.0")), UpperBound(Unbounded)) })
DEBUG No cache entry for: https://download.pytorch.org/whl/cpu/torch/
DEBUG No cache entry for: https://download.pytorch.org/whl/cpu/torchvision/
DEBUG Found fresh response for: https://pypi.org/simple/torchvision/
DEBUG Found fresh response for: https://pypi.org/simple/torch/
DEBUG Searching for a compatible version of torch{platform_system != 'Darwin'} (>=2.5.1)
DEBUG Selecting: torch==2.5.1+cpu [compatible] (torch-2.5.1+cpu-cp312-cp312-linux_x86_64.whl)
DEBUG Adding transitive dependency for torch==2.5.1+cpu: torch==2.5.1+cpu
DEBUG Adding transitive dependency for torch==2.5.1+cpu: torch{platform_system != 'Darwin'}==2.5.1+cpu
DEBUG Searching for a compatible version of torch{platform_system != 'Darwin'} (==2.5.1+cpu)
DEBUG Selecting: torch==2.5.1+cpu [compatible] (torch-2.5.1+cpu-cp312-cp312-linux_x86_64.whl)
DEBUG Found stale response for: https://download.pytorch.org/whl/cpu/torch-2.5.1%2Bcpu-cp312-cp312-linux_x86_64.whl#sha256=4856f9d6925121d13c2df07aa7580b767f449dfe71ae5acde9c27535d5da4840
DEBUG Sending revalidation request for: https://download.pytorch.org/whl/cpu/torch-2.5.1%2Bcpu-cp312-cp312-linux_x86_64.whl#sha256=4856f9d6925121d13c2df07aa7580b767f449dfe71ae5acde9c27535d5da4840
DEBUG Found not-modified response for: https://download.pytorch.org/whl/cpu/torch-2.5.1%2Bcpu-cp312-cp312-linux_x86_64.whl#sha256=4856f9d6925121d13c2df07aa7580b767f449dfe71ae5acde9c27535d5da4840
DEBUG Adding transitive dependency for torch==2.5.1+cpu: filelock*
DEBUG Adding transitive dependency for torch==2.5.1+cpu: fsspec*
DEBUG Adding transitive dependency for torch==2.5.1+cpu: jinja2*
DEBUG Adding transitive dependency for torch==2.5.1+cpu: networkx*
DEBUG Adding transitive dependency for torch==2.5.1+cpu: setuptools{python_full_version >= '3.12'}*
DEBUG Adding transitive dependency for torch==2.5.1+cpu: sympy{python_full_version >= '3.9'}>=1.13.1, <1.13.1+
DEBUG Adding transitive dependency for torch==2.5.1+cpu: typing-extensions>=4.8.0
DEBUG Searching for a compatible version of torch (==2.5.1+cpu)
DEBUG Selecting: torch==2.5.1+cpu [compatible] (torch-2.5.1+cpu-cp312-cp312-linux_x86_64.whl)
DEBUG Adding transitive dependency for torch==2.5.1+cpu: filelock*
DEBUG Adding transitive dependency for torch==2.5.1+cpu: fsspec*
DEBUG Adding transitive dependency for torch==2.5.1+cpu: jinja2*
DEBUG Adding transitive dependency for torch==2.5.1+cpu: networkx*
DEBUG Adding transitive dependency for torch==2.5.1+cpu: setuptools{python_full_version >= '3.12'}*
DEBUG Adding transitive dependency for torch==2.5.1+cpu: sympy{python_full_version >= '3.9'}>=1.13.1, <1.13.1+
DEBUG Adding transitive dependency for torch==2.5.1+cpu: typing-extensions>=4.8.0
DEBUG Searching for a compatible version of torchvision{platform_system != 'Darwin'} (>=0.20.1)
DEBUG Selecting: torchvision==0.20.1+cpu [compatible] (torchvision-0.20.1+cpu-cp312-cp312-linux_x86_64.whl)
DEBUG Adding transitive dependency for torchvision==0.20.1+cpu: torchvision==0.20.1+cpu
DEBUG Adding transitive dependency for torchvision==0.20.1+cpu: torchvision{platform_system != 'Darwin'}==0.20.1+cpu
DEBUG Searching for a compatible version of torchvision{platform_system != 'Darwin'} (==0.20.1+cpu)
DEBUG Selecting: torchvision==0.20.1+cpu [compatible] (torchvision-0.20.1+cpu-cp312-cp312-linux_x86_64.whl)
DEBUG Found stale response for: https://download.pytorch.org/whl/cpu/torchvision-0.20.1%2Bcpu-cp312-cp312-linux_x86_64.whl#sha256=5f46c7ac7f00a065cb40bfb1e1bfc4ba16a35f5d46b3fe70cca6b3cea7f822f7
DEBUG Sending revalidation request for: https://download.pytorch.org/whl/cpu/torchvision-0.20.1%2Bcpu-cp312-cp312-linux_x86_64.whl#sha256=5f46c7ac7f00a065cb40bfb1e1bfc4ba16a35f5d46b3fe70cca6b3cea7f822f7
DEBUG Found not-modified response for: https://download.pytorch.org/whl/cpu/torchvision-0.20.1%2Bcpu-cp312-cp312-linux_x86_64.whl#sha256=5f46c7ac7f00a065cb40bfb1e1bfc4ba16a35f5d46b3fe70cca6b3cea7f822f7
DEBUG Adding transitive dependency for torchvision==0.20.1+cpu: numpy*
DEBUG Adding transitive dependency for torchvision==0.20.1+cpu: pillow>=5.3.0, <8.3.dev0 | >=8.4.dev0
DEBUG Adding transitive dependency for torchvision==0.20.1+cpu: torch>=2.5.1, <2.5.1+
DEBUG Searching for a compatible version of torchvision (==0.20.1+cpu)
DEBUG Selecting: torchvision==0.20.1+cpu [compatible] (torchvision-0.20.1+cpu-cp312-cp312-linux_x86_64.whl)
DEBUG Adding transitive dependency for torchvision==0.20.1+cpu: numpy*
DEBUG Adding transitive dependency for torchvision==0.20.1+cpu: pillow>=5.3.0, <8.3.dev0 | >=8.4.dev0
DEBUG Adding transitive dependency for torchvision==0.20.1+cpu: torch>=2.5.1, <2.5.1+
DEBUG Searching for a compatible version of filelock (*)
DEBUG Selecting: filelock==3.16.1 [preference] (filelock-3.16.1-py3-none-any.whl)
DEBUG Searching for a compatible version of fsspec (*)
DEBUG Selecting: fsspec==2024.10.0 [preference] (fsspec-2024.10.0-py3-none-any.whl)
DEBUG Searching for a compatible version of jinja2 (*)
DEBUG Selecting: jinja2==3.1.4 [preference] (jinja2-3.1.4-py3-none-any.whl)
DEBUG Adding transitive dependency for jinja2==3.1.4: markupsafe>=2.0
DEBUG Searching for a compatible version of networkx (*)
DEBUG Selecting: networkx==3.4.2 [preference] (networkx-3.4.2-py3-none-any.whl)
DEBUG Searching for a compatible version of setuptools{python_full_version >= '3.12'} (*)
DEBUG Selecting: setuptools==75.6.0 [preference] (setuptools-75.6.0-py3-none-any.whl)
DEBUG Adding transitive dependency for setuptools==75.6.0: setuptools==75.6.0
DEBUG Adding transitive dependency for setuptools==75.6.0: setuptools{python_full_version >= '3.12'}==75.6.0
DEBUG Searching for a compatible version of setuptools{python_full_version >= '3.12'} (==75.6.0)
DEBUG Selecting: setuptools==75.6.0 [preference] (setuptools-75.6.0-py3-none-any.whl)
DEBUG Searching for a compatible version of setuptools (==75.6.0)
DEBUG Selecting: setuptools==75.6.0 [preference] (setuptools-75.6.0-py3-none-any.whl)
DEBUG Searching for a compatible version of sympy{python_full_version >= '3.9'} (>=1.13.1, <1.13.1+)
DEBUG Selecting: sympy==1.13.1 [preference] (sympy-1.13.1-py3-none-any.whl)
DEBUG Adding transitive dependency for sympy==1.13.1: sympy==1.13.1
DEBUG Adding transitive dependency for sympy==1.13.1: sympy{python_full_version >= '3.9'}==1.13.1
DEBUG Searching for a compatible version of sympy{python_full_version >= '3.9'} (==1.13.1)
DEBUG Selecting: sympy==1.13.1 [preference] (sympy-1.13.1-py3-none-any.whl)
DEBUG Adding transitive dependency for sympy==1.13.1: mpmath>=1.1.0, <1.4
DEBUG Searching for a compatible version of sympy (==1.13.1)
DEBUG Selecting: sympy==1.13.1 [preference] (sympy-1.13.1-py3-none-any.whl)
DEBUG Adding transitive dependency for sympy==1.13.1: mpmath>=1.1.0, <1.4
DEBUG Searching for a compatible version of typing-extensions (>=4.8.0)
DEBUG Selecting: typing-extensions==4.12.2 [preference] (typing_extensions-4.12.2-py3-none-any.whl)
DEBUG Searching for a compatible version of numpy (*)
DEBUG Selecting: numpy==2.1.3 [preference] (numpy-2.1.3-cp312-cp312-macosx_10_13_x86_64.whl)
DEBUG Searching for a compatible version of pillow (>=5.3.0, <8.3.dev0 | >=8.4.dev0)
DEBUG Selecting: pillow==11.0.0 [preference] (pillow-11.0.0-cp312-cp312-macosx_10_13_x86_64.whl)
DEBUG Searching for a compatible version of markupsafe (>=2.0)
DEBUG Selecting: markupsafe==3.0.2 [preference] (MarkupSafe-3.0.2-cp312-cp312-macosx_10_13_universal2.whl)
DEBUG Searching for a compatible version of mpmath (>=1.1.0, <1.4)
DEBUG Selecting: mpmath==1.3.0 [preference] (mpmath-1.3.0-py3-none-any.whl)
DEBUG Tried 41 versions: filelock 2, fsspec 2, jinja2 2, markupsafe 2, mpmath 2, networkx 2, numpy 2, pillow 2, project 2, setuptools 2, sympy 2, torch 2, torchvision 2, typing-extensions 2, nvidia-cublas-cu12 1, nvidia-cuda-cupti-cu12 1, nvidia-cuda-nvrtc-cu12 1, nvidia-cuda-runtime-cu12 1, nvidia-cudnn-cu12 1, nvidia-cufft-cu12 1, nvidia-curand-cu12 1, nvidia-cusolver-cu12 1, nvidia-cusparse-cu12 1, nvidia-nccl-cu12 1, nvidia-nvjitlink-cu12 1, nvidia-nvtx-cu12 1, triton 1
DEBUG split `platform_system != 'Darwin'` resolution took 0.935s
DEBUG Solving split (platform_system == 'Darwin') (requires-python: RequiresPython { specifiers: VersionSpecifiers([VersionSpecifier { operator: GreaterThanEqual, version: "3.12.0" }]), range: RequiresPythonRange(LowerBound(Included("3.12.0")), UpperBound(Unbounded)) })
DEBUG Searching for a compatible version of torch{platform_system == 'Darwin'} (>=2.5.1)
DEBUG Selecting: torch==2.5.1 [compatible] (torch-2.5.1-cp312-cp312-manylinux1_x86_64.whl)
DEBUG Adding transitive dependency for torch==2.5.1: torch==2.5.1
DEBUG Adding transitive dependency for torch==2.5.1: torch{platform_system == 'Darwin'}==2.5.1
DEBUG Searching for a compatible version of torch{platform_system == 'Darwin'} (==2.5.1)
DEBUG Selecting: torch==2.5.1 [compatible] (torch-2.5.1-cp312-cp312-manylinux1_x86_64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/8b/5c/36c114d120bfe10f9323ed35061bc5878cc74f3f594003854b0ea298942f/torch-2.5.1-cp312-cp312-manylinux1_x86_64.whl.metadata
DEBUG Adding transitive dependency for torch==2.5.1: filelock*
DEBUG Adding transitive dependency for torch==2.5.1: fsspec*
DEBUG Adding transitive dependency for torch==2.5.1: jinja2*
DEBUG Adding transitive dependency for torch==2.5.1: networkx*
DEBUG Adding transitive dependency for torch==2.5.1: setuptools{python_full_version >= '3.12'}*
DEBUG Adding transitive dependency for torch==2.5.1: sympy{python_full_version >= '3.9'}>=1.13.1, <1.13.1+
DEBUG Adding transitive dependency for torch==2.5.1: typing-extensions>=4.8.0
DEBUG Searching for a compatible version of torch (==2.5.1)
DEBUG Selecting: torch==2.5.1 [compatible] (torch-2.5.1-cp312-cp312-manylinux1_x86_64.whl)
DEBUG Adding transitive dependency for torch==2.5.1: filelock*
DEBUG Adding transitive dependency for torch==2.5.1: fsspec*
DEBUG Adding transitive dependency for torch==2.5.1: jinja2*
DEBUG Adding transitive dependency for torch==2.5.1: networkx*
DEBUG Adding transitive dependency for torch==2.5.1: setuptools{python_full_version >= '3.12'}*
DEBUG Adding transitive dependency for torch==2.5.1: sympy{python_full_version >= '3.9'}>=1.13.1, <1.13.1+
DEBUG Adding transitive dependency for torch==2.5.1: typing-extensions>=4.8.0
DEBUG Searching for a compatible version of torchvision{platform_system == 'Darwin'} (>=0.20.1)
DEBUG Selecting: torchvision==0.20.1 [compatible] (torchvision-0.20.1-cp312-cp312-macosx_11_0_arm64.whl)
DEBUG Adding transitive dependency for torchvision==0.20.1: torchvision==0.20.1
DEBUG Adding transitive dependency for torchvision==0.20.1: torchvision{platform_system == 'Darwin'}==0.20.1
DEBUG Searching for a compatible version of torchvision{platform_system == 'Darwin'} (==0.20.1)
DEBUG Selecting: torchvision==0.20.1 [compatible] (torchvision-0.20.1-cp312-cp312-macosx_11_0_arm64.whl)
DEBUG Found fresh response for: https://files.pythonhosted.org/packages/c5/eb/4ba19616378f2bc085999432fded2b7dfdbdccc6dd0fc293203452508100/torchvision-0.20.1-cp312-cp312-macosx_11_0_arm64.whl.metadata
DEBUG Adding transitive dependency for torchvision==0.20.1: numpy*
DEBUG Adding transitive dependency for torchvision==0.20.1: pillow>=5.3.0, <8.3.dev0 | >=8.4.dev0
DEBUG Adding transitive dependency for torchvision==0.20.1: torch>=2.5.1, <2.5.1+
DEBUG Searching for a compatible version of torchvision (==0.20.1)
DEBUG Selecting: torchvision==0.20.1 [compatible] (torchvision-0.20.1-cp312-cp312-macosx_11_0_arm64.whl)
DEBUG Adding transitive dependency for torchvision==0.20.1: numpy*
DEBUG Adding transitive dependency for torchvision==0.20.1: pillow>=5.3.0, <8.3.dev0 | >=8.4.dev0
DEBUG Adding transitive dependency for torchvision==0.20.1: torch>=2.5.1, <2.5.1+
DEBUG Searching for a compatible version of filelock (*)
DEBUG Selecting: filelock==3.16.1 [preference] (filelock-3.16.1-py3-none-any.whl)
DEBUG Searching for a compatible version of fsspec (*)
DEBUG Selecting: fsspec==2024.10.0 [preference] (fsspec-2024.10.0-py3-none-any.whl)
DEBUG Searching for a compatible version of jinja2 (*)
DEBUG Selecting: jinja2==3.1.4 [preference] (jinja2-3.1.4-py3-none-any.whl)
DEBUG Adding transitive dependency for jinja2==3.1.4: markupsafe>=2.0
DEBUG Searching for a compatible version of networkx (*)
DEBUG Selecting: networkx==3.4.2 [preference] (networkx-3.4.2-py3-none-any.whl)
DEBUG Searching for a compatible version of setuptools{python_full_version >= '3.12'} (*)
DEBUG Selecting: setuptools==75.6.0 [preference] (setuptools-75.6.0-py3-none-any.whl)
DEBUG Adding transitive dependency for setuptools==75.6.0: setuptools==75.6.0
DEBUG Adding transitive dependency for setuptools==75.6.0: setuptools{python_full_version >= '3.12'}==75.6.0
DEBUG Searching for a compatible version of setuptools{python_full_version >= '3.12'} (==75.6.0)
DEBUG Selecting: setuptools==75.6.0 [preference] (setuptools-75.6.0-py3-none-any.whl)
DEBUG Searching for a compatible version of setuptools (==75.6.0)
DEBUG Selecting: setuptools==75.6.0 [preference] (setuptools-75.6.0-py3-none-any.whl)
DEBUG Searching for a compatible version of sympy{python_full_version >= '3.9'} (>=1.13.1, <1.13.1+)
DEBUG Selecting: sympy==1.13.1 [preference] (sympy-1.13.1-py3-none-any.whl)
DEBUG Adding transitive dependency for sympy==1.13.1: sympy==1.13.1
DEBUG Adding transitive dependency for sympy==1.13.1: sympy{python_full_version >= '3.9'}==1.13.1
DEBUG Searching for a compatible version of sympy{python_full_version >= '3.9'} (==1.13.1)
DEBUG Selecting: sympy==1.13.1 [preference] (sympy-1.13.1-py3-none-any.whl)
DEBUG Adding transitive dependency for sympy==1.13.1: mpmath>=1.1.0, <1.4
DEBUG Searching for a compatible version of sympy (==1.13.1)
DEBUG Selecting: sympy==1.13.1 [preference] (sympy-1.13.1-py3-none-any.whl)
DEBUG Adding transitive dependency for sympy==1.13.1: mpmath>=1.1.0, <1.4
DEBUG Searching for a compatible version of typing-extensions (>=4.8.0)
DEBUG Selecting: typing-extensions==4.12.2 [preference] (typing_extensions-4.12.2-py3-none-any.whl)
DEBUG Searching for a compatible version of numpy (*)
DEBUG Selecting: numpy==2.1.3 [preference] (numpy-2.1.3-cp312-cp312-macosx_10_13_x86_64.whl)
DEBUG Searching for a compatible version of pillow (>=5.3.0, <8.3.dev0 | >=8.4.dev0)
DEBUG Selecting: pillow==11.0.0 [preference] (pillow-11.0.0-cp312-cp312-macosx_10_13_x86_64.whl)
DEBUG Searching for a compatible version of markupsafe (>=2.0)
DEBUG Selecting: markupsafe==3.0.2 [preference] (MarkupSafe-3.0.2-cp312-cp312-macosx_10_13_universal2.whl)
DEBUG Searching for a compatible version of mpmath (>=1.1.0, <1.4)
DEBUG Selecting: mpmath==1.3.0 [preference] (mpmath-1.3.0-py3-none-any.whl)
DEBUG Tried 54 versions: filelock 3, fsspec 3, jinja2 3, markupsafe 3, mpmath 3, networkx 3, numpy 3, pillow 3, setuptools 3, sympy 3, torch 3, torchvision 3, typing-extensions 3, project 2, nvidia-cublas-cu12 1, nvidia-cuda-cupti-cu12 1, nvidia-cuda-nvrtc-cu12 1, nvidia-cuda-runtime-cu12 1, nvidia-cudnn-cu12 1, nvidia-cufft-cu12 1, nvidia-curand-cu12 1, nvidia-cusolver-cu12 1, nvidia-cusparse-cu12 1, nvidia-nccl-cu12 1, nvidia-nvjitlink-cu12 1, nvidia-nvtx-cu12 1, triton 1
DEBUG split `platform_system == 'Darwin'` resolution took 0.035s
DEBUG Searching for a compatible version of project @ file:///C:/Users/jeanp/code/tmp (*)
DEBUG Tried 55 versions: filelock 3, fsspec 3, jinja2 3, markupsafe 3, mpmath 3, networkx 3, numpy 3, pillow 3, project 3, setuptools 3, sympy 3, torch 3, torchvision 3, typing-extensions 3, nvidia-cublas-cu12 1, nvidia-cuda-cupti-cu12 1, nvidia-cuda-nvrtc-cu12 1, nvidia-cuda-runtime-cu12 1, nvidia-cudnn-cu12 1, nvidia-cufft-cu12 1, nvidia-curand-cu12 1, nvidia-cusolver-cu12 1, nvidia-cusparse-cu12 1, nvidia-nccl-cu12 1, nvidia-nvjitlink-cu12 1, nvidia-nvtx-cu12 1, triton 1
DEBUG all marker environments resolution took 0.002s
INFO Solved your requirements for 4 environments
DEBUG Distinct solution for split (platform_system != 'Darwin') with 15 packages
DEBUG Distinct solution for split (platform_system == 'Darwin') with 15 packages
Resolved 31 packages in 2.17s
error: Distribution `torch==2.5.1+cu124 @ registry+https://download.pytorch.org/whl/cu124` can't be installed because it doesn't have a source distribution or wheel for the current platform
```

</details>

I'm on Windows with CUDA and an amd CPU
The wheel uv is looking for exists: https://download.pytorch.org/whl/cu124/torch-2.5.1%2Bcu124-cp312-cp312-win_amd64.whl#sha256=3c3f705fb125edbd77f9579fa11a138c56af8968a10fc95834cdd9fdf4f1f1a6

**Comment by charliermarsh** [comment]
You're trying to install on Python 3.13: `Solving with installed Python version: 3.13.0`

**Comment by jplumail** [comment]
Oh thanks! with ``--python 3.12` it now works.

**Comment by charliermarsh** [comment]
Sweet!
